[settings]
windows_shim_mode = "hardlink"

[tools]
rust = "1.89.0"
zig = "0.15.2"

"aqua:JohnnyMorganz/StyLua" = { version = "latest", exe = "stylua" }
"aqua:ajeetdsouza/zoxide" = "latest"
"aqua:shellspec/shellspec" = "latest"
"aqua:starship/starship" = "latest"
"github:cli/cli" = { version = "latest", exe = "gh" }
"gitlab:gitlab-org/cli" = { version = "latest", exe = "glab" }
