[tools]
deno = "2.1.4"
duckdb = "latest"
elixir = "1.18.3-otp-27"
erlang = "27.2"
go = "1.24.0"
lua = "5.4.7"
node = "latest"
python = "3.13.1"
rust = "1.89.0"
sqlite = "latest"
usage = "latest"
zig = "latest"

"aqua:99designs/aws-vault" = "latest"
"aqua:BurntSushi/ripgrep" = "latest"
"aqua:JohnnyMorganz/StyLua" = { version = "latest", exe = "stylua" }
"aqua:PaulJuliusMartinez/jless" = "latest"
"aqua:antonmedv/fx" = "latest"
"aqua:atuinsh/atuin" = "latest"
"aqua:casey/just" = "latest"
"aqua:chmln/sd" = "latest"
"aqua:ismaelgv/rnr" = "latest"
"aqua:junegunn/fzf" = "latest"
"aqua:koalaman/shellcheck" = "latest"
"aqua:mikefarah/yq" = "latest"
"aqua:muesli/duf" = "latest"
"aqua:mvdan/sh" = "latest"
"aqua:sharkdp/bat" = "latest"
"aqua:sharkdp/fd" = "latest"
"aqua:shellspec/shellspec" = "latest"
"aqua:starship/starship" = "latest"
"aqua:sxyazi/yazi" = "latest"
"aqua:tealdeer-rs/tealdeer" = "latest"
"asdf:mise-plugins/mise-eza" = "latest"
"github:BLAKE3-team/BLAKE3" = { version = "latest", exe = "BLAKE3", rename_exe = "b3sum" }
"github:FiloSottile/age" = "latest"
"github:avencera/rustywind" = "latest"
"github:cli/cli" = { version = "latest", exe = "gh" }
"github:tailwindlabs/tailwindcss" = "latest"
"github:theseus-rs/rsql" = "latest"
"gitlab:gitlab-org/cli" = { version = "latest", exe = "glab" }
cosign = "latest"
"aqua:exercism/cli" = "latest"
dmd = "nightly"

